{% set version = "2.11.9" %}

package:
  name: types-jinja2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-jinja2/types-Jinja2-{{ version }}.tar.gz
  sha256: dbdc74a40aba7aed520b7e4d89e8f0fe4286518494208b35123bcf084d4b8c81

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - types-markupsafe

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/jinja2-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Jinja2
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
